/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type DecisionCard = {
  _type: "decisionCard";
  heading: string;
  decisionText: string;
  tradeoffText: string;
};

export type UxFlowStep = {
  _type: "uxFlowStep";
  stepNumber: string;
  label: string;
  description: string;
};

export type MetaLink = {
  _type: "metaLink";
  label: string;
  url: string;
};

export type SummaryPoint = {
  _type: "summaryPoint";
  label: string;
  text: string;
};

export type OpenSourceProject = {
  _id: string;
  _type: "openSourceProject";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  description: string;
  githubUrl: string;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  showExperiments?: boolean;
  showOpenSourceProjects?: boolean;
};

export type ArticleLink = {
  _id: string;
  _type: "articleLink";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  publicationAndRole: string;
  title: string;
  url: string;
  order: number;
};

export type ExperienceEntry = {
  _id: string;
  _type: "experienceEntry";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  dateRange: string;
  location?: string;
  role: string;
  description: string;
  dotColor: "primary" | "secondary" | "tertiary" | "soft" | "magenta";
  order: number;
  compact?: boolean;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  order: number;
  statusLabel: string;
  statusPillColor: "primary" | "secondary" | "tertiary" | "soft";
  accentColor: "primary" | "tertiary";
  mainImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  summaryPoints?: Array<
    {
      _key: string;
    } & SummaryPoint
  >;
  techTags?: Array<string>;
  liveUrl?: string;
  liveUrlLabel?: string;
  githubUrl?: string;
  hasCaseStudy?: boolean;
  subtitle?: string;
  role?: string;
  timelineLabel?: string;
  timelineValue?: string;
  stackText?: string;
  metaLinks?: Array<
    {
      _key: string;
    } & MetaLink
  >;
  problemBody?: string;
  uxFlowImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  uxFlowPlaceholderLabel?: string;
  uxFlowSteps?: Array<
    {
      _key: string;
    } & UxFlowStep
  >;
  decisions?: Array<
    {
      _key: string;
    } & DecisionCard
  >;
  outcomeHeading?: string;
  outcomeBody?: string;
  outcomeCtaLabel?: string;
  outcomeCtaUrl?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | DecisionCard
  | UxFlowStep
  | MetaLink
  | SummaryPoint
  | OpenSourceProject
  | SiteSettings
  | ArticleLink
  | ExperienceEntry
  | SanityImageAssetReference
  | Project
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/lib/sanity/queries.ts
// Variable: projectsQuery
// Query: *[_type == "project"] | order(order asc)
export type ProjectsQueryResult = Array<{
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  order: number;
  statusLabel: string;
  statusPillColor: "primary" | "secondary" | "soft" | "tertiary";
  accentColor: "primary" | "tertiary";
  mainImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  summaryPoints?: Array<
    {
      _key: string;
    } & SummaryPoint
  >;
  techTags?: Array<string>;
  liveUrl?: string;
  liveUrlLabel?: string;
  githubUrl?: string;
  hasCaseStudy?: boolean;
  subtitle?: string;
  role?: string;
  timelineLabel?: string;
  timelineValue?: string;
  stackText?: string;
  metaLinks?: Array<
    {
      _key: string;
    } & MetaLink
  >;
  problemBody?: string;
  uxFlowImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  uxFlowPlaceholderLabel?: string;
  uxFlowSteps?: Array<
    {
      _key: string;
    } & UxFlowStep
  >;
  decisions?: Array<
    {
      _key: string;
    } & DecisionCard
  >;
  outcomeHeading?: string;
  outcomeBody?: string;
  outcomeCtaLabel?: string;
  outcomeCtaUrl?: string;
}>;

// Source: src/lib/sanity/queries.ts
// Variable: projectBySlugQuery
// Query: *[_type == "project" && slug.current == $slug][0]
export type ProjectBySlugQueryResult = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  order: number;
  statusLabel: string;
  statusPillColor: "primary" | "secondary" | "soft" | "tertiary";
  accentColor: "primary" | "tertiary";
  mainImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  summaryPoints?: Array<
    {
      _key: string;
    } & SummaryPoint
  >;
  techTags?: Array<string>;
  liveUrl?: string;
  liveUrlLabel?: string;
  githubUrl?: string;
  hasCaseStudy?: boolean;
  subtitle?: string;
  role?: string;
  timelineLabel?: string;
  timelineValue?: string;
  stackText?: string;
  metaLinks?: Array<
    {
      _key: string;
    } & MetaLink
  >;
  problemBody?: string;
  uxFlowImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  uxFlowPlaceholderLabel?: string;
  uxFlowSteps?: Array<
    {
      _key: string;
    } & UxFlowStep
  >;
  decisions?: Array<
    {
      _key: string;
    } & DecisionCard
  >;
  outcomeHeading?: string;
  outcomeBody?: string;
  outcomeCtaLabel?: string;
  outcomeCtaUrl?: string;
} | null;

// Source: src/lib/sanity/queries.ts
// Variable: projectSlugsQuery
// Query: *[_type == "project" && hasCaseStudy == true]{ "slug": slug.current }
export type ProjectSlugsQueryResult = Array<{
  slug: string;
}>;

// Source: src/lib/sanity/queries.ts
// Variable: experienceEntriesQuery
// Query: *[_type == "experienceEntry"] | order(order asc)
export type ExperienceEntriesQueryResult = Array<{
  _id: string;
  _type: "experienceEntry";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  dateRange: string;
  location?: string;
  role: string;
  description: string;
  dotColor: "magenta" | "primary" | "secondary" | "soft" | "tertiary";
  order: number;
  compact?: boolean;
}>;

// Source: src/lib/sanity/queries.ts
// Variable: articleLinksQuery
// Query: *[_type == "articleLink"] | order(order asc)
export type ArticleLinksQueryResult = Array<{
  _id: string;
  _type: "articleLink";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  publicationAndRole: string;
  title: string;
  url: string;
  order: number;
}>;

// Source: src/lib/sanity/queries.ts
// Variable: openSourceProjectQuery
// Query: *[_type == "openSourceProject"] | order(order asc)
export type OpenSourceProjectQueryResult = Array<{
  _id: string;
  _type: "openSourceProject";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  description: string;
  githubUrl: string;
}>;

// Source: src/lib/sanity/queries.ts
// Variable: siteSettingsQuery
// Query: *[_type == "siteSettings"][0]
export type SiteSettingsQueryResult = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  showExperiments?: boolean;
  showOpenSourceProjects?: boolean;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "project"] | order(order asc)': ProjectsQueryResult;
    '*[_type == "project" && slug.current == $slug][0]': ProjectBySlugQueryResult;
    '*[_type == "project" && hasCaseStudy == true]{ "slug": slug.current }': ProjectSlugsQueryResult;
    '*[_type == "experienceEntry"] | order(order asc)': ExperienceEntriesQueryResult;
    '*[_type == "articleLink"] | order(order asc)': ArticleLinksQueryResult;
    '*[_type == "openSourceProject"] | order(order asc)': OpenSourceProjectQueryResult;
    '*[_type == "siteSettings"][0]': SiteSettingsQueryResult;
  }
}
