import { defineArrayMember, defineField, defineType } from "sanity";

export const project = defineType({
  name: "project",
  title: "Project",
  type: "document",
  groups: [
    { name: "card", title: "Homepage card" },
    { name: "caseStudy", title: "Case study" },
  ],
  fields: [
    // -- Card --
    defineField({
      name: "title",
      title: "Title",
      type: "string",
      group: "card",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "slug",
      title: "Slug",
      type: "slug",
      group: "card",
      options: { source: "title" },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "order",
      title: "Order",
      description: "Lower numbers appear first on the homepage.",
      type: "number",
      group: "card",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "statusLabel",
      title: "Status label",
      description: 'e.g. "Side project · Live", "Product · MVP"',
      type: "string",
      group: "card",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "statusPillColor",
      title: "Status pill color",
      type: "string",
      group: "card",
      options: {
        list: [
          { title: "Primary", value: "primary" },
          { title: "Secondary", value: "secondary" },
          { title: "Tertiary", value: "tertiary" },
          { title: "Soft", value: "soft" },
        ],
      },
      initialValue: "secondary",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "accentColor",
      title: "Accent color",
      description: "Used for link underlines and case-study step numbers.",
      type: "string",
      group: "card",
      options: {
        list: [
          { title: "Primary", value: "primary" },
          { title: "Tertiary", value: "tertiary" },
        ],
      },
      initialValue: "primary",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "mainImage",
      title: "Screenshot",
      type: "image",
      group: "card",
      options: { hotspot: true },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "summaryPoints",
      title: "Summary points",
      description: "Homepage card copy, e.g. Problem / What I built / Result.",
      type: "array",
      group: "card",
      of: [defineArrayMember({ type: "summaryPoint" })],
      validation: (rule) => rule.min(2).max(4),
    }),
    defineField({
      name: "techTags",
      title: "Tech tags",
      type: "array",
      group: "card",
      of: [defineArrayMember({ type: "string" })],
      options: { layout: "tags" },
    }),
    defineField({
      name: "liveUrl",
      title: "Live URL",
      type: "url",
      group: "card",
    }),
    defineField({
      name: "liveUrlLabel",
      title: "Live URL label",
      description: 'e.g. "Visit the table"',
      type: "string",
      group: "card",
      initialValue: "Visit live",
    }),
    defineField({
      name: "githubUrl",
      title: "GitHub URL",
      type: "url",
      group: "card",
    }),

    // -- Case study --
    defineField({
      name: "hasCaseStudy",
      title: "Has case study",
      description:
        'Gates whether "Read case study" renders and /work/[slug] resolves.',
      type: "boolean",
      group: "caseStudy",
      initialValue: true,
    }),
    defineField({
      name: "subtitle",
      title: "Subtitle",
      type: "text",
      rows: 2,
      group: "caseStudy",
    }),
    defineField({
      name: "role",
      title: "Role",
      type: "string",
      group: "caseStudy",
    }),
    defineField({
      name: "timelineLabel",
      title: "Timeline field label",
      description:
        'Usually "Timeline", RetroBox-style projects may use "Status".',
      type: "string",
      group: "caseStudy",
      initialValue: "Timeline",
    }),
    defineField({
      name: "timelineValue",
      title: "Timeline value",
      type: "string",
      group: "caseStudy",
    }),
    defineField({
      name: "stackText",
      title: "Stack",
      type: "string",
      group: "caseStudy",
    }),
    defineField({
      name: "metaLinks",
      title: "Meta links",
      type: "array",
      group: "caseStudy",
      of: [defineArrayMember({ type: "metaLink" })],
    }),
    defineField({
      name: "problemBody",
      title: "The problem",
      type: "text",
      rows: 4,
      group: "caseStudy",
    }),
    defineField({
      name: "uxFlowImage",
      title: "UX flow image",
      type: "image",
      group: "caseStudy",
      options: { hotspot: true },
    }),
    defineField({
      name: "uxFlowPlaceholderLabel",
      title: "UX flow placeholder label",
      description: "Shown when no UX flow image has been uploaded yet.",
      type: "string",
      group: "caseStudy",
    }),
    defineField({
      name: "uxFlowSteps",
      title: "UX flow steps",
      type: "array",
      group: "caseStudy",
      of: [defineArrayMember({ type: "uxFlowStep" })],
      validation: (rule) => rule.max(4),
    }),
    defineField({
      name: "decisions",
      title: "Key decisions & tradeoffs",
      type: "array",
      group: "caseStudy",
      of: [defineArrayMember({ type: "decisionCard" })],
      validation: (rule) => rule.max(3),
    }),
    defineField({
      name: "outcomeHeading",
      title: "Outcome heading",
      description:
        'Usually "Outcome", finished projects may use "Where it stands".',
      type: "string",
      group: "caseStudy",
      initialValue: "Outcome",
    }),
    defineField({
      name: "outcomeBody",
      title: "Outcome body",
      type: "text",
      rows: 4,
      group: "caseStudy",
    }),
    defineField({
      name: "outcomeCtaLabel",
      title: "Outcome CTA label",
      type: "string",
      group: "caseStudy",
    }),
    defineField({
      name: "outcomeCtaUrl",
      title: "Outcome CTA URL",
      type: "url",
      group: "caseStudy",
    }),
  ],
  preview: {
    select: { title: "title", subtitle: "statusLabel", media: "mainImage" },
  },
});
